version: '3.3'
services:
  postgres:
    image: postgres:10.5-alpine
    restart: always
    ports:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=pulse
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:3.2.12-alpine
    restart: always
    ports:
      - 6379
    volumes:
      - ./data/redis:/data

  php-fpm:
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    command: ["/app/scripts/repeat", "/app/bin/K", "worker"]
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV
      - DATABASE_URL
      - GOOGLE_ID
      - GOOGLE_SECRET
      - LOGIN_PROXY
      - POSTMARK_API_KEY
      - REDIS_URL
      - HONEYBADGER_API_KEY
      - POPUP_URL
      - MAX_ITERATIONS
      - DEV_EMAIL
