version: '3.3'
services:
  nginx:
    image: nginx:1.13.6-alpine
    restart: always
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - 80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
    ports:
      - 9000
    environment:
      - APP_ENV
      - DATABASE_URL
      - GOOGLE_ID
      - GOOGLE_SECRET
      - LOGIN_PROXY
      - REDIS_URL
      - HONEYBADGER_API_KEY
